# i3status configuration file.
# see "man i3status" for documentation.
# Nord theme - https://www.nordtheme.com/docs/colors-and-palettes

general {
        colors = true
        color_good = "#a3be8c"
        color_degraded = "#ebcb8b"
        color_bad = "#bf616a"
        interval = 5
}

# Original colors:
# color_good = "#00FF00" (default green)
# color_degraded = "#FFFF00" (default yellow)
# color_bad = "#FF0000" (default red)

order += "wireless _first_"
order += "ethernet _first_"
order += "battery all"
order += "disk /"
order += "cpu_usage"
order += "load"
order += "memory"
order += "tztime local"

wireless _first_ {
        format_up = " %essid %ip"
        format_down = " down"
}

ethernet _first_ {
        format_up = "󰈀 %ip (%speed)"
        format_down = "󰈀 down"
}

battery all {
        format = "%status %percentage %remaining"
        status_chr = " CHR"
        status_bat = " BAT"
        status_unk = " UNK"
        status_full = " FULL"
        low_threshold = 20
}

disk "/" {
        format = " DISK %avail"
}

cpu_usage {
        format = " CPU %usage"
}

memory {
        format = " MEM %used / %total"
        threshold_degraded = "1G"
        format_degraded = " MEM %available free"
}

load {
        format = " %1min/%5min/%15min"
}

tztime local {
        format = " %Y-%m-%d  %H:%M:%S"
}
